version: '2.3'

# create default network
networks:
  default:
    name: ros-network
    external: true

volumes:
  workspace:

services:

  robostack:
    build: ./
    image: wn1980/robostack-humble${TAG}
    container_name: robostack_humble
    init: true
    restart: unless-stopped
    privileged: true
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/run/systemd:/run/systemd"
      - "/etc/localtime:/etc/localtime:ro"
      - "workspace:/workspace"
      - "~/.gitconfig:/home/developer/.gitconfig"
    healthcheck:
      test: ["CMD-SHELL", "test -e /opt/conda/bin/conda"]
      interval: "1m"
      retries: 20
    environment:
      - ROS_DOMAIN_ID=50
      - DISPLAY=:9
    #ports:
    #  - "8559:8008"
    #  - "9902:6901"
    #command: conda run --no-capture-output -n ros_humble jupyter lab --no-browser --ip 0.0.0.0 --port=8888 --allow-root
    #command: jupyter lab --no-browser --ip 0.0.0.0 --port=8888 --allow-root
